name: Deploy Angular App to Cloud Run

on:
  push:
    branches:
      - main  # Despliega cuando se haga un push a la rama principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        credentials: ${{ secrets.GCP_CREDENTIALS_JSON }}

    - name: Build Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/angular-app:v1 .

    - name: Push Docker image to Google Container Registry
      run: |
        gcloud auth configure-docker
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/angular-app:v1

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy angular-app \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/angular-app:v1 \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
